const sitesData = {
    films: [
        {
            id: 'cinepulse',
            name: 'Cinepulse',
            logo: 'logoSites/Cinepulse.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'cinepulse.to <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>cinepulse.fr</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 28/05/2025'],
            url: 'https://cinepulse.to/',
            searchUrl: 'https://cinepulse.to/catalog?query={query}&sort-by=pertinence',
            featured: true,
            isNew: false,
            category: 'films'
        },
        {
            id: 'ivdid',
            name: 'IVDID',
            logo: 'logoSites/Ivdid.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'ivdid.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://ivdid.com/2alhobzy6/home/ivdid',
            searchUrl: '',
            featured: true,
            isNew: false,
            category: 'films'
        },
        {
            id: 'xalaflix',
            name: 'XalaFlix',
            logo: 'logoSites/xalaflix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'xalaflix.io <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 30/05/2025'],
            url: 'https://xalaflix.io/',
            searchUrl: '',
            featured: true,
            isNew: true,
            category: 'films'
        },
        {
            id: 'topstream',
            name: 'Topstream',
            logo: 'logoSites/TopStream.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'top-stream.io <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://top-stream.io',
            searchUrl: 'https://top-stream.io/search/{query}',
            featured: false,
            isNew: false,
            category: 'films'
        },
        {
            id: 'vfstream',
            name: 'VFStream',
            logo: 'logoSites/VfStream.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'films.vfstream.eu <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://films.vfstream.eu/',
            searchUrl: '',
            featured: false,
            isNew: false,
            category: 'films'
        },
        {
            id: '1jour1film',
            name: '1jour1film',
            logo: 'logoSites/1jour1film.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: '1jour1film22.online <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>1jour1film2.online</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 28/05/2025'],
            url: 'https://1jour1film22.online/',
            searchUrl: 'https://1jour1film22.online/?s={query}',
            featured: false,
            isNew: false,
            category: 'films'
        },
        {
            id: 'wowfilms',
            name: 'WOW-FILMS',
            logo: 'logoSites/WowFilms.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'wowfilms2.mom <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>wowfilms11.mom</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 28/05/2025'],
            url: 'https://wowfilms2.mom/',
            searchUrl: 'https://wowfilms2.mom/?s={query}',
            featured: true,
            isNew: false,
            category: 'films'
        },
        {
            id: 'senpaistream',
            name: 'Senpai-Stream',
            logo: 'logoSites/senpai-stream.svg',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'senpai-stream.art <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 01/06/2025'],
            url: 'https://senpai-stream.art/',
            searchUrl: 'https://senpai-stream.art/search/{query}',
            featured: true,
            isNew: true,
            category: 'films'
        },
    ],
    series: [
        {
            id: 'nightflix',
            name: 'NightFlix',
            logo: 'logoSites/NightFlix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'nightflix.run <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>nightflix.store</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://nightflix.run/',
            searchUrl: 'https://nightflix.run/recherche?q={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'wiflix',
            name: 'WiFlix',
            logo: 'logoSites/WiFlix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'flemmix.top <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>flemmix.net</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://flemmix.top/',
            searchUrl: 'https://flemmix.top/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'papadustream',
            name: 'PapaDuStream',
            logo: 'logoSites/PapaDuStream.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'papadustream.cash <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>papadustream.boo</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://papadustream.cash/',
            searchUrl: 'https://papadustream.cash/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'filmax',
            name: 'Filmax',
            logo: 'logoSites/filmax.svg',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'filmax.to <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://filmax.to/',
            searchUrl: 'https://filmax.to/search/{query}',
            featured: true,
            isNew: true,
            category: 'series'
        },
        {
            id: 'monstream',
            name: 'MonStream',
            logo: 'logoSites/MonStream.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'monstream.cafe <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://vww.monstream.cafe',
            searchUrl: 'https://vww.monstream.cafe/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'frenchstream',
            name: 'French-Stream',
            logo: 'logoSites/FrechStream.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'fsmirror87.lol <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>fsmirror77.lol</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://fsmirror87.lol/',
            searchUrl: 'https://fsmirror87.lol/index.php?story={query}&do=search&subaction=search',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'empirestreaming',
            name: 'Empire-Streaming',
            logo: 'logoSites/empirestreaming.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'empire-stream.space <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://empire-stream.space/',
            searchUrl: '',
            featured: true,
            isNew: true,
            category: 'series'
        },
        {
            id: 'coflix',
            name: 'Coflix',
            logo: 'logoSites/coflix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'coflix.mov <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://coflix.mov/',
            searchUrl: 'https://coflix.mov/?s={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'frembed',
            name: 'Frembed',
            logo: 'logoSites/frembed.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'frembed.site <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 30/05/2025'],
            url: 'https://frembed.site/',
            searchUrl: '',
            featured: true,
            isNew: true,
            category: 'series'
        },
        {
            id: 'wookafr',
            name: 'WookaFR',
            logo: 'logoSites/WookaFr.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'wookafr.tel <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>wookafr.app</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://wookafr.tel/',
            searchUrl: 'https://wookafr.tel/?s={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'movix',
            name: 'Movix',
            logo: 'logoSites/Movix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'movix.site <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.movix.site/',
            searchUrl: 'https://www.movix.site/search?q={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'netmirror',
            name: 'NetMirror',
            logo: 'logoSites/netmirror.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'netfree2.cc <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://netfree2.cc/home',
            searchUrl: '',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'sadisflix',
            name: 'Sadisflix',
            logo: 'logoSites/SadisFlix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'sadisflix-officiel.sbs <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>sadisflix.hair</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://sadisflix-officiel.sbs/',
            searchUrl: 'https://sadisflix-officiel.sbs/search?q={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'yopflix',
            name: 'YopFlix',
            logo: 'logoSites/YopFlix.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'yopflix.my <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>yopflix.pics</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 22/05/2025'],
            url: 'https://yopflix.my/',
            searchUrl: "https://yopflix.my/search?query={query}",
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'hdstream',
            name: 'Hdstream',
            logo: 'logoSites/10.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'hdstream.top <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 18/05/2025'],
            url: 'https://www.hdstream.top/',
            searchUrl: 'https://www.hdstream.top/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'dulourd',
            name: 'Dulourd',
            logo: 'logoSites/dulourd.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'dulourd.day <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.dulourd.day/',
            searchUrl: 'https://www.dulourd.day/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'filmoflix',
            name: 'FilmoFlix',
            logo: 'logoSites/FilmoFlix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'filmoflix.bz <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>filmoflix.is</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://filmoflix.bz/',
            searchUrl: 'https://filmoflix.bz/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'cinemay',
            name: 'Cinemay',
            logo: 'logoSites/cinemay.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'cinemay.cloud <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://cinemay.cloud/',
            searchUrl: 'https://cinemay.cloud/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'dustreaming',
            name: 'Dustreaming',
            logo: 'logoSites/dustreaming.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'dustreaming.info <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://dustreaming.info/',
            searchUrl: 'https://dustreaming.info/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'megastream',
            name: 'MegaStream',
            logo: 'logoSites/megastream.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'megastream.link <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://www.megastream.link/',
            searchUrl: 'https://www.megastream.link/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'megafilms',
            name: 'MegaFilms',
            logo: 'logoSites/megafilms.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'megafilms.click <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://www.megafilms.click/',
            searchUrl: 'https://www.megafilms.click/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'frenchflix',
            name: 'FrenchFlix',
            logo: 'logoSites/FrenchFlix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'frenchflix.cc <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://frenchflix.cc/',
            searchUrl: 'https://frenchflix.cc/?s={query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'netflax',
            name: 'NetFlax',
            logo: 'logoSites/netflax.jpg',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'netflax.fr <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 01/06/2025'],
            url: 'https://netflax.fr/',
            searchUrl: 'https://netflax.fr/search/{query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: 'sekostream',
            name: 'SekoStream',
            logo: 'logoSites/sekostream.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'seko-stream.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://seko-stream.com/',
            searchUrl: 'https://seko-stream.com/search/{query}',
            featured: true,
            isNew: false,
            category: 'series'
        },
        {
            id: '24drama',
            name: '24DRAMA (vostfr)',
            logo: 'logoSites/24drama.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: '24drama.to <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 30/05/2025'],
            url: 'https://24drama.to/',
            searchUrl: 'https://24drama.to/search?q={query}',
            featured: true,
            isNew: true,
            category: 'series'
        },
    ],
    dll: [
        {
            id: 'darkiworld',
            name: 'Darkiworld',
            logo: 'logoSites/darkiworld.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'darkiworld2025.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>darki-tometjerry.com</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 25/05/2025'],
            url: 'https://darkiworld2025.com/',
            searchUrl: 'https://darkiworld2025.com/search/{query}',
            featured: true,
            isNew: false,
            category: 'dll'
        },
        {
            id: 'wawacity',
            name: 'Wawacity',
            logo: 'logoSites/wawacity.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'wawacity.pictures <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>wawacity.pet</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 23/05/2025'],
            url: 'https://www.wawacity.pictures/',
            searchUrl: 'https://www.wawacity.pictures/?search={query}&p=films',
            featured: true,
            isNew: false,
            category: 'dll'
        },
        {
            id: 'zonetelechargement',
            name: 'Zone Téléchargement',
            logo: 'logoSites/zonetelechargement.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'zone-telechargement.picture <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://www.zone-telechargement.pictures/',
            searchUrl: 'https://www.zone-telechargement.pictures/?p=films&search={query}',
            featured: true,
            isNew: true,
            category: 'dll'
        },
        {
            id: 'extremedownload',
            name: 'Extreme Downlaod',
            logo: 'logoSites/extremedownload.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'extreme-down.pictures <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://www.extreme-down.pictures/',
            searchUrl: 'https://www.extreme-down.pictures/?p=films&search={query}',
            featured: true,
            isNew: true,
            category: 'dll'
        },
        {
            id: 'tirexo',
            name: 'Tirexo',
            logo: 'logoSites/tirexo.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'tirexo.pictures <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://www.tirexo.pictures/',
            searchUrl: 'https://www.tirexo.pictures/?search={query}&p=films',
            featured: true,
            isNew: true,
            category: 'dll'
        },
    ],
    animes: [
        {
            id: 'animekai',
            name: 'AnimeKai',
            logo: 'logoSites/AnimeKai.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'animekai.to <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://animekai.to/',
            searchUrl: 'https://animekai.to/browser?keyword={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'animesama',
            name: 'AnimeSama',
            logo: 'logoSites/AnimeSama.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'anime-sama.fr <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://anime-sama.fr/',
            searchUrl: '',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'frenchanime',
            name: 'FrenchAnime',
            logo: 'logoSites/FrenchAnime.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'french-anime.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://french-anime.com/',
            searchUrl: 'https://french-anime.com/index.php?do=search&subaction=search&search_start=0&full_search=0&story={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'franime',
            name: 'FRAnime',
            logo: 'logoSites/FRAnime.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'franime.fr <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://franime.fr/',
            searchUrl: 'https://franime.fr/recherche?search={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'frenchmanga',
            name: 'French-Manga',
            logo: 'logoSites/frenchmanga.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'w14.french-manga.net <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 01/06/2025'],
            url: 'https://w14.french-manga.net/',
            searchUrl: 'https://w14.french-manga.net/index.php?story={query}&do=search&subaction=search',
            featured: true,
            isNew: true,
            category: 'animes'
        },
        {
            id: 'empireanime',
            name: 'Empire-Anime',
            logo: 'logoSites/empire-anime.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'empire-anime.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 29/05/2025'],
            url: 'https://empire-anime.com/',
            searchUrl: '',
            featured: true,
            isNew: true,
            category: 'animes'
        },
        {
            id: 'voiranime',
            name: 'Voiranime',
            logo: 'logoSites/VoirAnime.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'v6.voiranime.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://v6.voiranime.com/',
            searchUrl: 'https://v6.voiranime.com/?s={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'vostfree',
            name: 'Vostfree',
            logo: 'logoSites/vostfree.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'vostfree.ws <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 31/05/2025'],
            url: 'https://vostfree.ws/',
            searchUrl: 'https://vostfree.ws/index.php?do={query}',
            featured: true,
            isNew: true,
            category: 'animes'
        },
        {
            id: '24drama',
            name: '24DRAMA',
            logo: 'logoSites/24drama.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: '24drama.to <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 30/05/2025'],
            url: 'https://24drama.to/',
            searchUrl: 'https://24drama.to/search?q={query}',
            featured: true,
            isNew: true,
            category: 'animes'
        },
        {
            id: 'mavanimes',
            name: 'Mavanimes',
            logo: 'logoSites/MavAnimes.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'mavanimes.co <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.mavanimes.co/',
            searchUrl: 'https://www.mavanimes.co/?s={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'yukiflix',
            name: 'YukiFlix',
            logo: 'logoSites/YukiFlix.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'yukiflix.pythonanywhere.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://yukiflix.pythonanywhere.com/decouvrir',
            searchUrl: 'https://yukiflix.pythonanywhere.com/search?q={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'animesite',
            name: 'AnimeSite',
            logo: 'logoSites/AnimeSite.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'https://animesite.fr <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://animesite.fr/',
            searchUrl: 'https://animesite.fr/search/{query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'ryokaianime',
            name: 'RyokaiAnime',
            logo: 'logoSites/ryokaianime.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'ryokaianime.fr <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://ryokaianime.fr/',
            searchUrl: 'https://ryokaianime.fr/search/{query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'jetanimes',
            name: 'JetAnimes',
            logo: 'logoSites/JetAnimes.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'on.jetanimes.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://on.jetanimes.com/',
            searchUrl: 'https://on.jetanimes.com/?s={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
        {
            id: 'vostanime',
            name: 'VostAnime',
            logo: 'logoSites/vostanime.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'ww4.vostanime.fr <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>ww2.vostanime.fr</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 01/06/2025'],
            url: 'https://ww4.vostanime.fr/',
            searchUrl: 'https://ww4.vostanime.fr/?s={query}',
            featured: true,
            isNew: false,
            category: 'animes'
        },
    ],
    drama: [
        {
            id: 'kisskh',
            name: 'KissKh',
            logo: 'logoSites/512x512bb-removebg-preview.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'kisskh.co <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://kisskh.co/',
            searchUrl: '',
            featured: true,
            isNew: false,
            category: 'drama'
        },
        {
            id: 'voirdrama',
            name: 'VoirDrama',
            logo: 'logoSites/VoirDrama.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'voirdrama.org <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://voirdrama.org/',
            searchUrl: 'https://voirdrama.org/?post_type=wp-manga&s={query}',
            featured: true,
            isNew: false,
            category: 'drama'
        },
        {
            id: 'dramacool',
            name: 'DramaCool',
            logo: 'logoSites/dramacool.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'dramacool.com.de <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://ww5.dramacool.com.de/',
            searchUrl: 'https://ww5.dramacool.com.de/search?keyword={query}',
            featured: true,
            isNew: false,
            category: 'drama'
        },
        {
            id: 'myasiantv',
            name: 'MyAsianTv',
            logo: 'logoSites/myasiantv.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'myasiantv.rest <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://ww3.myasiantv.rest/',
            searchUrl: 'https://ww3.myasiantv.rest/?s={query}',
            featured: true,
            isNew: false,
            category: 'drama'
        },
        {
            id: 'kissasian',
            name: 'KissAsian',
            logo: 'logoSites/kissasian.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'kissasian.nl <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://kissasian.nl/',
            searchUrl: 'https://kissasian.nl/search/drama?keyword={query}&x=0&y=0',
            featured: true,
            isNew: false,
            category: 'drama'
        },
        {
            id: 'dramacountdown',
            name: 'DramaCountDown',
            logo: 'logoSites/dramacountdown.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'dramacountdown.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://dramacountdown.com/',
            searchUrl: 'https://dramacountdown.com/search?q={query}',
            featured: true,
            isNew: false,
            category: 'drama'
        },
    ],
    torrent: [
        {
            id: 'thepiratebay',
            name: 'The Pirate Bay',
            logo: 'logoSites/tpb.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'thepiratebay10.info <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://thepiratebay10.info/',
            searchUrl: 'https://thepiratebay10.info/search/{query}/1/99/0',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: '1337x',
            name: '1337X',
            logo: 'logoSites/logo.svg',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: '1337x.to <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://1337x.to/',
            searchUrl: 'https://1337x.to/search/{query}/1/',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'oxtorrent',
            name: 'OxTorrent',
            logo: 'logoSites/oxtorrent.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'oxtorrent5.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i><br><s>oxtorrent3.com</s> <i class="fa-solid fa-x" style="color: #ff0000;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.oxtorrent5.com/home',
            searchUrl: 'https://www.oxtorrent5.com/recherche/{query}',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'yggtorrent',
            name: 'YggTorrent',
            logo: 'logoSites/ygg.svg',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'yggtorrent3.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.yggtorrent3.com/home',
            searchUrl: 'https://www.yggtorrent3.com/recherche/{query}',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'cpasbien',
            name: 'Cpasbien',
            logo: 'logoSites/cpasbien.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'cpasbien4.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.cpasbien4.com/home',
            searchUrl: 'https://www.cpasbien4.com/recherche/{query}',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'torrent9',
            name: 'Torrent9',
            logo: 'logoSites/torrent9.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'torrent9.to <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 30/05/2025'],
            url: 'https://torrent9.to/',
            searchUrl: 'https://torrent9.to/search_torrent/{query}.html',
            featured: true,
            isNew: true,
            category: 'torrent'
        },
        {
            id: 'zetorrents',
            name: 'Zetorrents',
            logo: 'logoSites/zetorrents.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'zetorrents1.com <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.zetorrents1.com/home',
            searchUrl: 'https://www.zetorrents1.com/recherche/{query}',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'torrent9',
            name: 'Torrentz9',
            logo: 'logoSites/torrentz.svg',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'torrentz9.org <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://torrentz9.org/',
            searchUrl: 'https://torrentz9.org/search?keyword={query}',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'limetorrents',
            name: 'LimeTorrents',
            logo: 'logoSites/limetorrents.webp',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'limetorrents.lol <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://www.limetorrents.lol/',
            searchUrl: 'https://www.limetorrents.lol/search/all/{query}/',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'bingebrowser',
            name: 'Binge Browser',
            logo: 'logoSites/binge.ico',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'binge-browser.vercel.app <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://binge-browser.vercel.app/',
            searchUrl: 'https://binge-browser.vercel.app/?search_query={query}',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'nyaa',
            name: 'Nyaa',
            logo: 'logoSites/nyaa.png',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'nyaa.land <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 17/05/2025'],
            url: 'https://nyaa.land/',
            searchUrl: 'https://nyaa.land/?f=0&c=0_0&q={query}',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
        {
            id: 'yts',
            name: 'YTS',
            logo: 'logoSites/YTS.svg',
            headerBg: 'linear-gradient(135deg,rgb(113, 63, 204) 0%,rgb(173, 147, 250) 100%)',
            description: 'yts.mx <i class="fa-solid fa-check" style="color: #63E6BE;"></i>',
            tags: ['Update : 19/05/2025'],
            url: 'https://yts.mx/',
            searchUrl: 'https://yts.mx/browse-movies/{query}/all/all/0/latest/0/all',
            featured: true,
            isNew: false,
            category: 'torrent'
        },
    ]
};